### PR TITLE
Add CI using Gambit builds from main repo

### PR DESCRIPTION
**Pull request by daviwil**
Hey @feeley, here's a demo of a CI workflow downloading the most recent Gambit build from CI on `master` of the Gambit repo using the new custom GitHub Action [daviwil/download-gambit](https://github.com/daviwil/download-gambit).  Once the Gambit build is downloaded, I can run the tests in `test.scm` successfully.  I think this is a good example for how CI on all Gambit module repos could work!

You can see the output of a test run here: https://github.com/daviwil/hello/runs/717382764?check_suite_focus=true

Ultimately I'd like to move `daviwil/download-gambit` into the Gambit org at some point, but that doesn't have to happen yet for it to be useful.

/cc @lassik

### CODE REVIEW

**Comment by feeley** [comment]
Nice!  It seems to only take a few seconds to download Gambit, which will really help with the module development workflow.  Wonderful!

If you want to reproduce the normal usage you should probably install the module and run `gsi github.com/gambit/hello/test`.  Normally that will output a summary of the tests which I don't see in the log... I wonder why.  Also if you want to avoid the output you could run `gsi _test/quiet github.com/gambit/hello/test`.

Also I wonder how the module could indicate on which version(s) of Gambit it is supposed to work.  Always assuming the latest Gambit is not ideal because as Gambit evolves some old modules will no longer pass their tests (which is good on one hand, but not if you only care about a specific set of "popular"/"stable"/"favourite"/... Gambit versions).  At a minimum it should be possible to say "test with the latest release of Gambit" instead of the default "test with Gambit HEAD" (where failing tests could be due to hickups in the development of Gambit and not the logic of the module).  Also a module may be implemented with shims to allow it to run on different versions of Gambit, so we might want to say "all releases of Gambit since v4.5.3 except v4.9.1".

This could be generalized to other Scheme implementations, in the spirit of Scheme community building and sharing of modules.  Of course this is a much more difficult thing to achieve but perhaps worth keeping in mind as a future goal.

**Comment by daviwil** [comment]
The test log shows up in the Windows runs but curiously not in Linux or macOS, I'll have to look into that.

Some kind of metadata file could be useful for supported version ranges, one that is checked in at the top level of the module repo (sort of like a `package.json`).  Alternatively you could imagine some added syntax to `define-library` that could specify this, but then we'd be drawing outside the lines of R7RS.

At least for downloading Gambit builds in CI, I'm setting up `download-gambit` so that you'll be able to download builds both from any CI workflow or release tag, so we'll be able to control that on a per-repo basis (and also be able to do multiple runs for different Gambit versions if necessary).

Thanks for merging this!  We'll need to make sure there's an `ARTIFACT_TOKEN` set up on this repo otherwise the Gambit artifact downloading won't work.  Unfortunately the GitHub APIs don't let you hit the artifact download URL without being authenticated :/

**Comment by lassik** [comment]
> Also I wonder how the module could indicate on which version(s) of Gambit it is supposed to work. Always assuming the latest Gambit is not ideal because as Gambit evolves some old modules will no longer pass their tests (which is good on one hand, but not if you only care about a specific set of "popular"/"stable"/"favourite"/... Gambit versions). At a minimum it should be possible to say "test with the latest release of Gambit" instead of the default "test with Gambit HEAD" (where failing tests could be due to hickups in the development of Gambit and not the logic of the module). Also a module may be implemented with shims to allow it to run on different versions of Gambit, so we might want to say "all releases of Gambit since v4.5.3 except v4.9.1".

What is the "main file" of a Gambit module? Is it the `.sld` with the `define-library` form?

**Comment by feeley** [comment]
Yes, the module can contain "toplevel" forms inside the `define-library` that will be executed when the library is loaded.  So that can be used for a "main".

**Comment by lassik** [comment]
If the define-library is the top-level form, the compatibility information about Gambit versions should probably be another extension to the R7RS define-library syntax?

Would be nice if the same syntax was supported by other Scheme implementations as well.

**Comment by feeley** [comment]
> If the define-library is the top-level form, the compatibility information about Gambit versions should probably be another extension to the R7RS define-library syntax?
> 
> Would be nice if the same syntax was supported by other Scheme implementations as well.

Not quite... the version information in an `(import (mylib @X))` means that version X of `mylib` is required.  The version information I'm talking about is for testing that the library works on Gambit versions A, B, and C.  So it is not the same kind of version information.

I guess if the `import` clause allowed `(import (gambit @(any-of A B C)))` something could be worked out but that will become hairy very quickly (you want to be able to specify ranges of versions, skipping some versions, etc).

**Comment by feeley** [comment]
And what you really want is

```
(import (any-of (gambit @4.9.3)
                (gambit @4.9.4)
                (chez @5.0)
                ...)
```

But without actually importing anything...

**Comment by lassik** [comment]
I meant something like:

```scheme
(define-library (foo)
  (scheme-implementation (gambit 5.x))
  (import (gambit base) (gambit string))
  ...)
```

So adding new forms inside the `define-library` but outside `import`. In a similar vein as Gambit now has some pkg-config forms.

**Comment by feeley** [comment]
But what is the syntax and semantics of `(scheme-implementation (gambit 5.x))`?  How do you specify multiple versions?  How do you say `(gambit HEAD)`, etc?

**Comment by lassik** [comment]
Those details would have to be worked out. I don't have a concrete design in mind yet.

**Comment by lassik** [comment]
[Snow-fort packages](http://snow-fort.org/pkg) have `package.scm` metadata files like this:

```scheme
(package
  (maintainers "Alex Shinn <alexshinn@gmail.com>")
  (authors "Alex Shinn <alexshinn@gmail.com>")
  (version "0.7.3")
  (license bsd)
  (library
    (name
      (chibi sxml))
    (path "chibi/sxml.sld")
    (depends
      (scheme base)
      (scheme write)))
  (manual "chibi/sxml.html")
  (description "Utilities to convert sxml to xml or plain text."))
```

We could also start from that and make something good for all Scheme implementations. That syntax is already good for all of R7RS, but as far as I know it cannot encode implementation-specific idiosyncratic features a la `cond-expand`.

**Comment by feeley** [comment]
But what/who is the consumer for this metadata?  I already see some issues with the above... for example version information should be implicit in the VCS and the dependencies and name should be in the `define-library`.  I'm not sure what `path` means.  So just to say that this seems to impose a certain set of properties that are not universal.

**Comment by lassik** [comment]
> But what/who is the consumer for this metadata?

There would be multiple consumers:

* Scheme package managers
* Scheme implementations that can auto-download packages
* All tools dealing with package indexes (query tools, web renderers, ...)

> version information should be implicit in the VCS

Agreed that manual version information easily gets out of hand. But it's useful if a program can auto-generate VCS-independent tarballs of packages and encode the version information in them. It would be great to think of some notation that discourages people from writing the version number manually but automated tools could still insert it.

Those snow-fort S-exp files are auto-generated by a command like `snow-chibi --version=1.0 ...`. But that command still takes the `--version` manually instead of getting it from git.

> the dependencies and name should be in the `define-library`.

Agreed. This information is a 1:1 duplicate.

> I'm not sure what `path` means.

The relative filename inside the package tarball of the Scheme source file containing the `define-library` form.

> So just to say that this seems to impose a certain set of properties that are not universal.

Snow-fort does require all of those properties AFAIK, but for wider use many of them could be made optional.

**Comment by daviwil** [comment]
I agree, this kind of information is useful as @lassik describes.  All of it is pretty much standard in many language ecosystems (`package.json` (JavaScript), `Cargo.toml` (Rust), `.gemspec` (Ruby), etc).  It's definitely not information that `gsc` needs, but there will be tools for Gambit and other Schemes that will benefit from it.

With that in mind, I don't think it's something `gsc` itself should have to support such a file format; I'd rather there be another tool at a higher level that is used for orchestrating applicaton/library builds via `gsc`, packaging, releasing, etc.  I could also imagine having a GitHub repo that maintains a list of Gambit module repos which automatically reads these files to gather the metadata to present both a Markdown-based list and a collection that would be searchable by other means.

**Comment by feeley** [comment]
I understand that this is for tools that are external to `gsc` but nevertheless, possibly internal to the Gambit system (which has a beginning of a package manager).  Also I don't want to duplicate information that is available another way (for example the version information that is stored implicitly in the VCS).  Metadata like you suggest is "static" and suitable for when you take a snapshot of a repo at a particular point of its evolution.  But modern VCS are more flexible because a repo contains the whole history of the code's evolution, so the metadata for the repo is much more complex (in a sense one "static" metadata per commit).

Gambit's module system was designed to address the "dependency hell" problem by allowing multiple versions of modules to be installed and even coexist in an executable at run time.  A static metadata for modules would be a step in the wrong direction.

One option would be for the metadata to not contain the version information but rather to contain the metadata of multiple versions and indexed by the version.  Food for thought.

Another issue is that Gambit allows a package to contain more than one module.  It can contain a single module, or a main module and submodules, or multiple modules each with submodules (or even no module!).  A package is equated with a git repository.  So it is the package that has a version and not the contained modules (or put another way all the contained modules have the same version in sync).

So it would be good to define exactly what is meant with the term "package" when talking about a Scheme package's metadata. How is a "package" used by a Scheme system? How is a "package" distributed? etc I suspect that the snow-fort views a package as a snapshot of a single module's source code (in other words, source code implementing a single module and identified with a name and version).  I think the "single module per package" model is too restrictive.  It is useful to put in the same place modules that are related and that work hand-in-hand, and also to create modular modules, i.e. modules that are built out of submodules. So having a package metadata that assumes the "single module per package" model is also a step in the wrong direction.  I think a package should be viewed as a versioned set of related modules.

Finally, I think custom package repositories are rather "old school"... package repositories should be built upon modern VCS servers such as github and gitlab which have lots of advantages. Reproducing those features in a custom repository is a lot of work for a small community and it will never keep up with the growing features of VCS servers. Why reinvent the wheel?

**Comment by lassik** [comment]
> So it would be good to define exactly what is meant with the term "package" when talking about a Scheme package's metadata.

Indeed, I've long been bothered by that term. "Package" and "library" are similar-but-different terms and it seems gratuitous to have both. "Library" is what is defined by RnRS. "Package" is a cluster of one or more libraries. But since RnRS defines a way for libraries to import other libraries, couldn't "packages" be implicit by simply tracing the imports? What's the benefit in manually clustering libraries into packages?

**Comment by lassik** [comment]
I think the concept of an explicit "package" was a more useful when package managers connected to the internet weren't ubiquitous. Back then it was genuinely difficult to chase down all the dependencies so bundling them up manually was clearly useful. The benefit is no longer as clear.

**Comment by lassik** [comment]
"Package = VCS repo" is a useful association under some circumstances, but there are also repos that have multiple packages, and a big package can be split across repos. Would it work to be concerned with libraries only?

If multiple libraries are in one repo, the commit/tag could serve as the version number for all of them.

**Comment by lassik** [comment]
Re: terminology, Gambit currently uses the related terms "library", "module" and "namespace". These seem like different aspects of the same basic system - could the terms be unified at some point?

**Comment by feeley** [comment]
To me "importing" a module/library is not the same thing as "containing" a submodule.  You want to separate the outside view of a thing and the inner workings.  So you might want to import a main module that is modularized into smaller modules, but you want to keep the abstract view that only one module is involved (really the inner modularization is not the business of external clients of the module).

I view a "package" as a collection of useful things (Scheme modules but also data and possibly modules in other languages) that are somehow related and that expect to be "in sync".  In my mind I also associate "package" with the notion of a maintainer (individual or organization) that decides what is included in the package and also is responsible for making the content evolve and ensuring that all the parts of the package are consistent with each other.  Beyond the package boundary (where unknown developers are involved) there are no guarantees.

That view of packages is a close fit to VCS repos and it has the benefit of allowing the reuse of all the VCS machinery.  Given that "package" is a rather vague term to start with I don't see an issue to defining it to be equivalent to "VCS repo". Another way of seeing it is that this is not inventing a totally new concept... it is just giving a name to what we have been doing in our day-to-day development work for a while with git or other VCS, with hopefully few additional constraints (like repository structure).

**Comment by feeley** [comment]
> Re: terminology, Gambit currently uses the related terms "library", "module" and "namespace". These seem like different aspects of the same basic system - could the terms be unified at some point?

The term `library` is usually reserved for R7RS libraries.  The term `module` is more generic and means "a unit of code (usually aiming a certain set of related functionalities)".  The term `namespace` is related to how global variable names are partitioned to avoid clashes.  They are loosely related to libraries (by default each version of a library will get its own unique namespace), but there are ways to bypass that (and in some cases good reasons to).  For example `_thread` and `_num` are two modules but they share the same namespace, so that for example `make-thread` and `sqrt` can be used without import declarations, and their name stays lightweight:

```
> make-thread       
#<procedure #2 make-thread>
> sqrt              
#<procedure #3 sqrt>
> (import (srfi 28))
> format            
#<procedure #4 srfi/28#format>
```

**Comment by daviwil** [comment]
I'm 100% in favor of treating repository forges like GitHub/Lab as the "package" repository, I think it's a forward-looking concept.  There's a new evolution of Node inspired by Go called Deno which really leans in to this concept.  It seems like they also eschew metadata files entirely and imports refer directly to module files inside of a GitHub repository:

https://deno.land/manual/linking_to_external_code

Here's their package "repository", it's basically just a simple index of packages with references to their repositories: https://deno.land/x

It'd be interesting for Gambit to have something like the above just to make it easier to find Gambit modules, but as @feeley told me once before, users can just search for them on GitHub.  Maybe instead of having an "official" module list this should be the responsibility of community repos like [awesome-scheme](https://github.com/schemedoc/awesome-scheme).

**Comment by feeley** [comment]
@daviwil Thanks for pointing out Deno!  It is quite similar to what Gambit's modules are doing.  It uses URLs in imports for identifying modules, including an `@VVV` to indicate which version.  Also a repo is a group of modules, and they use relative path notation to refer to other modules in the same package.

Having an easily searchable list of Gambit packages in a centralized place would be great and probably a better user experience than a Google or github search.  Even better would be a searchable list of Scheme packages that indicate on which Scheme systems they work.  But it may be hard to reach consensus on the "right approach" among Schemers, so perhaps we should start something for Gambit and keep an eye on what the Scheme community decides, if ever.  I think Gambit's model for packages is probably too specialized for general acceptance by the Scheme community, but we shall see.

**Comment by daviwil** [comment]
An official Gambit package listing would be excellent.  I like how simple Deno's approach is, just maintaining a JSON file that (ostensibly) gets used as the data source for a static website.  Another thing to tinker with sometime!

**Pull request merged**
